### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by DelphicOkami** [markahesketh/ansible-role-ufw#1]
@markahesketh A tag would be really nice, this is a decent role I just want to control the version

**Comment by DelphicOkami** [comment]
I mean git tag BTW

**Comment by markahesketh** [comment]
Hi Michael,

I've merged your PR and created a git tag for the release:
https://github.com/markahesketh/ansible-role-ufw/tree/v1.1.0

Thanks for the PR and kind words.
